### ISSUE TITLE
tradeOffers event

### ISSUE THREAD

**Issue by ebildude123** [Konstaduck/node-steam-tradehandler#1]
I have a question about the tradeOffers event.
Is it only triggered when there is a new trade offer received?
Right now, it is not being triggered by a trade offer I have received before starting the bot.
Thanks

**Comment by Konstaduck** [comment]
Hey. Thank you for the good question.

This is bit tricky, because description of the tradeOffers event is: "Your number of pending incoming trade offers has changed.". And that's the problem. When bot is online, and offer comes, this event is passed because conditions are filled. However, when bot goes online and there is one offer already, it doesn't t pass because amount of offers doesn't change, until new one comes in.

I'm looking for solution on this one. I'll update my main script to support these kind of trades as well.

**Comment by ebildude123** [comment]
Instead of waiting for tradeoffer event, maybe can just run loop with sleep at end so it keeps checking

**Comment by ebildude123** [comment]
setInterval seems to work just fine instead of depending on the event being triggered

**Comment by Konstaduck** [comment]
Issue closed, this will be fixed on port to node-steam 1.0
